### ISSUE TITLE
로그인 과정에서 오류가 발생합니다.

### ISSUE THREAD

**Issue by needleworm** [elbakramer/koapy#11]
with KiwoomOpenApiContext() as context:
        # 로그인 예시
        context.EnsureConnected()

위 코드 실행시 아래와 같은 메시지가 출력되며 오류가 발생합니다.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\needl\Desktop\stockauto_kiwoom\project_env\lib\site-packages\koapy\context\KiwoomOpenApiContext.py", line 35, in __init__
    assert self._client.is_ready()
AssertionError

**Comment by elbakramer** [comment]
안녕하세요. 리포트 감사합니다.

공유주신 로그를 봤을때 아래 두가지중 하나일 듯 싶습니다.

1. 64bit 에서 서버 생성을 시도하면서 서버 생성이 실패함
2. 서버 생성이 오래걸려서 클라이언트 접속시도 과정에서 타임아웃

제 생각에는 1번의 가능성이 커보이는데요. 하단 OpenAPI OCX 가 32bit 환경만 지원하는 이유라서요.
똑같은 것을 32ibt 에서 다시 한번 돌려보시는 것을 추천드립니다.

2번의 경우라면 `context` 생성시 `client_check_timeout` 인자의 값을 `10` 초 이상으로 길게 넣어보는것도 시도해볼만 합니다.

그리고 최근 `v0.3.2` 버전으 릴리즈가 있었으니 업그레이드도 한번 해보시길 바랍니다.
업그레이드 후 기존의 `KiwoomOpenApiContext` 가 `KiwoomOpenApiPlusEntrypoint` 로 바뀌지만
다른 사용방식에서는 큰 차이는 없습니다.

업그레이드 이후의 예시 스크립트는 아래 링크를 참고 바랍니다.

https://github.com/elbakramer/koapy/blob/master/koapy/examples/06_main_scenario.py

**Comment by elbakramer** [comment]
추가적인 활동이 없어서 이슈 닫습니다. 필요하다면 언제든지 다시 열어주세요.
