### ISSUE TITLE
인스톨 후 'koapy' 애러

### ISSUE THREAD

**Issue by ajujoa** [elbakramer/koapy#111]
'pip install koapy' 이후 제대로 된 인스톨이었는지 확인하기위해 터미널에서 koapy 치면 아래처럼 나옵니다.
제대로 인스톨이 안되었는지 기본 예제에서부터 애러가 뜹니다.

1. 아나콘다 인스톨  Anaconda3-2021.04-Windows-x86_64 (파이썬 3.8 버전)
2. 아나콘다 프롬프트 conda update conda
3. 아나콘다 프롬프트 conda update --all
4. 아나콘다 프롬프트 python -m pip install --upgrade pip
5. 아나콘다 프롬프트 set CONDA_FORCE_32BIT=1
6. 아나콘다 프롬프트 conda create -n x86 python=3.8 anaconda
7. 아나콘다 프롬프트 conda activate x86
8. 아나콘다 프롬프트 python 으로 x32 버전 확인 [첨부 스샷]
9. 아나콘다 프롬프트 pip install koapy
10. 아나콘다 프롬프트 koapy [첨부 스샷]

![2023-07-24 16 50 34](https://github.com/elbakramer/koapy/assets/96732137/657134da-6d3e-45b0-b002-0e0ccd3b3624)

![2023-07-24 17 01 12](https://github.com/elbakramer/koapy/assets/96732137/a16a0c00-4184-41d7-b73a-4085dc6e9798)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python Version: Python 3.8 64Bit -> 32Bit env
 - KOAPY Version: v0.9.0 [Latest]

**Comment by ajujoa** [comment]
'poetry' 이용한 개발환경 구축 도움말 보고 일단 구동은 성공했습니다.
'pip install koapy'로는 제대로 구동이 안되네요. 
무슨 이유인지는 잘 모르겠습니다.
윈도우도 새로 깔아보고 VMWARE로 윈도우 버전 다른 걸로도 해보고 하다가 일단은 되니
기본 예제부터 해보겠습니다.
블로그나 유투브 등. 초보를 위한 자료가 더 있었으면 좋겠네요.

**Comment by uglymon** [comment]
늦었지만 저도 같은상황에서 astunparse 를 설치하니 잘 구동됩니다.

```shell
pip install astunparse
```
