### ISSUE TITLE
no module named koapy.comp 

### ISSUE THREAD

**Issue by danhojin** [elbakramer/koapy#12]
**Describe the bug**
예시 스크립트 실행시 3행 no module named koapy.comp에서 no module named koapy.comp 오류 발생

**To Reproduce**
README.rst 파일의  예시 스크립트를 저장한 후 그대로 그대로 실행해 보았을 때 처음 만나는 오류입니다.  miniconda의 python3.8 64bit설치 후 koapi 0.3.1 패키지를 pip을 통하여 설치하였습니다. ipython 쉘에서 실행해 보아도 다음과 같은 오류가 발생합니다.

(base) C:\Users\danho\proj\trading2021v1\koapy>ipython
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from koapy import KiwoomOpenApiPlusEntrypoint
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-edf4bbe0b3eb> in <module>
----> 1 from koapy import KiwoomOpenApiPlusEntrypoint

~\miniconda3\lib\site-packages\koapy\__init__.py in <module>
      5 __version__ = '0.3.1'
      6
----> 7 from koapy.backend.kiwoom_open_api_plus.core.KiwoomOpenApiPlusQAxWidget import KiwoomOpenApiPlusQAxWidget
      8 from koapy.backend.kiwoom_open_api_plus.core.KiwoomOpenApiPlusEntrypoint import KiwoomOpenApiPlusEntrypoint
      9 from koapy.backend.kiwoom_open_api_plus.core.KiwoomOpenApiPlusError import KiwoomOpenApiPlusError

~\miniconda3\lib\site-packages\koapy\backend\kiwoom_open_api_plus\core\KiwoomOpenApiPlusQAxWidget.py in <module>
----> 1 from koapy.compat.pyside2.QtWidgets import QWidget
      2 from koapy.compat.pyside2.QtAxContainer import QAxWidget
      3 from koapy.compat.pyside2.QtCore import QEvent, Qt
      4
      5 from koapy.backend.kiwoom_open_api_plus.core.KiwoomOpenApiPlusDynamicCallable import KiwoomOpenApiPlusDynamicCallable

ModuleNotFoundError: No module named 'koapy.compat'

In [2]:

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python Version: Python 3.8 64bit
 - KOAPY Version: 0.3.1

**Comment by elbakramer** [comment]
안녕하세요. 리포트 감사합니다.

공유주신 에러와 관련해서 https://github.com/elbakramer/koapy/commit/d3102db6ff78963a6b98fef5d23f8ec9d00f7464 커밋으로 대응해보았습니다.

구체적으로 `koapy.compat` 을 패키지형태로 인식하도록 `__init__.py` 가 추가되었어야 하던게 누락되었었네요.
그 동안 제 로컬 개발환경에서는 별 문제 없이 잘 돌았던 것 같은데 거 참 이상하군요;; (캐시 이슈인듯 합니다..)

해당 패치된 버전을 `v0.3.2` 로 릴리즈 해 놓았으니 버전 업데이트 후 사용해보시기 바랍니다.

---

추가로 첨언드리자면, 하단에서 사용하는 OpenAPI OCX 라이브러리가 32bit 만을 지원하기 때문에 32bit 환경에서 돌려주셔야 정상적으로 동작합니다. 64bit 환경에서 사용하기 위해서는 아래 문서의 내용과 비슷하게 32bit 환경에서 별도로 서버를 띄워놓은 이후에 64bit 환경에서 기존 코드 수정없이 동일하게 `KiwoomOpenApiPlusEntrypoint` 객체를 통해서 사용이 가능합니다.

https://koapy.readthedocs.io/en/latest/usage.html#grpc-server

서버-클라이언트 내용과 관련해서는 아래 예시 스트립트의 커멘트 내용도 한번 확인해보시면 좋을 것 같습니다.

https://github.com/elbakramer/koapy/blob/master/koapy/examples/05_koapy_entrypoint.py

**Comment by danhojin** [comment]
안녕하세요, python 3.8 32bit 버전을 miniconda를 통해 새로 설치하여 확인해 보니 잘 작동합니다. 
koapy 0.3.3입니다. https://koapy.readthedocs.io/en/latest/usage.html 링크의 예제에서 기대하는 결과를 출력해 주었습니다.
koapi 패키지를 처음 사용하는 사용자인지라, 예제를 좀 살펴보면서 더 확인해 보겠습니다.
