### ISSUE TITLE
tr : opt10072, opt10073 실행시 multi_data가 안넘어 오는 현상 문의

### ISSUE THREAD

**Issue by hoiwhs** [elbakramer/koapy#26]
먼저 이렇게 편하고 좋은 API를 공유해 주셔서 감사합니다.
현재 koapy를 가지고, 실매매 거래정보를 가져와 재구성하는 프로그램을 작성중 입니다.

예제의 하위함수를 통한 TR 요청을 이용하여,
TR번호 opt10072, opt10073 실행시 event.multi_data 가 생성되지 않아 문의 드립니다.

KOA StudioSA 2.20 버전에서 보면, 멀티데이터를 전달하나,
실행시, 멀티데이터값이 없습니다.

키움 HTS에 자동일지차트를 이용해서 보면, 실제 계좌에는 해당 기간동안 해당 종목을 여러번 실현손익한 정보는 있습니다. 

하기와 같이 TransactionCall을 이용하여, 호출하고 있습니다.

        rqname = '일자별종목별실현손익요청'
        trcode = 'opt10073'
        screen_no = '0001' # 화면번호, 0000 을 제외한 4자리 숫자 임의로 지정
        inputs = {'계좌번호' : acc,
                    '종목코드' : '253840',
                    '시작일자' : '20210620',
                    '종료일자' : '20210707',
                    }
        for event in self.entrypoint.TransactionCall(rqname, trcode, screen_no, inputs):
            print(event)
            columns = event.multi_data.names
            values = event.multi_data.values
            # columns = []
            records = []

            for values in values:
                records.append(self._RemoveLeadingZerosForNumbersInValues(values.values, 10))

TransactionCall 실행시, 하기 경고가 발생하여, 못가져 오는것으로 보입니다.
 **[WARNING] Repeat count greater than 0, but no multi data names available. - KiwoomOpenApiPlusEventHandlers.py:683**

서버에서 정보가 잘못전달 되는것인지, 도저히 확인이 되지 않아, 염치 불구하고 문의 드립니다.

참고로 **event.single_data**에는 최근 1개의 실현손익 정보가 들어가 있습니다.

도움주셔서 감사합니다.

![image](https://user-images.githubusercontent.com/44393764/124752214-8a005a00-df62-11eb-96b4-ab2d38cc2e44.png)

**Comment by elbakramer** [comment]
안녕하세요. 버그리포트 감사합니다.

현상 이해했구요. 서버가 잘못된건 아니고 KOAPY 구현상의 이슈로 보입니다.
차례차례 원인부터 설명드려보자면 아래와 같습니다.

KOAPY에서는 각 TR별 INPUT/OUTPUT 정보를 모듈이 설치된 위치의 데이터 파일들을 활용하여 추출 및 사용하고 있습니다.

<details>

---

관련 정보를 KOAStudio 를 보고 일일이 하드코딩 하는 것 말고는 방법이 없는건가.. 싶어서 찾아보다가 관련 파일들에 해당하는 정보가 있는거 같길레 이렇게 활용하도록 했네요.

OpenAPI 모듈이 기본위치에 설치된것을 가정했을때 `C:\OpenAPI\data\opt10001.enc` 따위의 파일들을 읽어서 분석하는데요.
현재 구현상으론 매번 해당 파일들을 읽진 않고 [미리 해당 파일들을 읽어서 분석 후 덤프해놓은 파일](https://github.com/elbakramer/koapy/blob/master/koapy/backend/kiwoom_open_api_plus/data/trinfo_by_code.json)을 활용하도록 되어있습니다.

(개발 당시에는 매번 임포트시 여러개의 파일을 읽게 되면 속도가 너무 느려지진 않을까 우려해서 저렇게 했는데요. 사실 모듈이 업데이트되면서 TR의 스펙이 혹시나 바뀌는 경우를 생각하면 매번 해당 파일들을 읽어서 처리하는게 더 정확할거 같아서 추후에는 매번 원본파일을 읽도록 수정할까 생각중이긴 합니다.)

참고로 아래는 관련 데이터 파일들을 읽고 분석해 덤프하는 부분의 코드입니다.
개발 당시 `dump_trinfo_by_code()` 함수를 호출해 `trinfo_by_code.json` 파일을 생성 및 업데이트 하였습니다.

https://github.com/elbakramer/koapy/blob/358bdf2a9cde32d57e56a5878b0aeec9554ec2e7/koapy/backend/kiwoom_open_api_plus/core/KiwoomOpenApiPlusTrInfo.py#L110-L262

---

</details>

다만 이렇게 데이터 파일을 읽어서 활용하는 방식에서 발견한 문제가 있는데요. 이들 중에 몇몇 TR에서는 실제 메뉴얼의 사용가이드와 다른 정보가 추출되는, 정확히는 **문서상으로 멀티데이터 출력을 가지고 실제로도 멀티데이터 출력을 읽는 방식으로 활용하는게 맞지만, 데이터 파일상으로는 싱글데이터 출력으로 보여지는** 문제가 있을 수 있습니다. (아마도 모듈 내부 시스템적인 동작과 외부 인터페이스간에 모종의 이유로 차이가 발생하는건 아닌가 추측만 하고 있습니다.)

해당 문제를 퀵하게 해결하기 위해서, 앞서 미리 덤프해두는 데이터는 별도 처리없이 원본 데이터에서 추출한 정보를 그대로 덤프한다는 것을 전제로 두고, 대신 **덤프파일을 읽을때 위와 같은 현상을 보이는 TR 들에 대해서 별도의 예외처리를 하도록** 현재는 구현이 되어있는데요. 이것 또한 제가 지금까지 테스트를 진행하면서 발견한 케이스들에 대해서만 처리를 하고 있어서, 아직 발견하지 못한 TR 들에 대해서는 이번과 비슷한 문제가 발생할 것으로 생각됩니다.

1차적인 해결방안으로는 아마도 공유주신 opt10072, opt10073 TR 에 대해서도 동일한 처리를 하도록 추가해야할 듯 싶구요.
적다보니 드는 생각인데, 말씀주신 warning 이 발생하는 케이스에 대해서 그냥 single 이 원래는 multi 였더라로 생각하고 multi 도 채워넣어서 반환해주도록 fallback 을 넣어주는것도 괜찮겠네요.

<details>

---

어떻게 KOAStudio 의 정보를 프로그램적으로 추출할 수 있는 방법이 있다면 지금의 방법보다 더욱 정확하겠지만 저는 해당 방법을 못찾겠네요. 아니면 모든 TR 에 대해서 하나씩 일일이 정확성을 확인하는 식으로 전수조사를 하던가 하면 되겠지만 엄두가 안나구요.

참고로 아래가 관련 예외처리를 하는것과 관련된 내용입니다.
구체적으로 `_SINGLE_TO_MULTI_TRCODES` 배열에 opt10072, opt10073 를 추가하면 될 것 같습니다.

https://github.com/elbakramer/koapy/blob/358bdf2a9cde32d57e56a5878b0aeec9554ec2e7/koapy/backend/kiwoom_open_api_plus/core/KiwoomOpenApiPlusTrInfo.py#L264-L304

---

</details>

**Comment by elbakramer** [comment]
https://github.com/elbakramer/koapy/commit/98a55cb6cc472340924ec1b3632a3a76b4cb942c 를 통해서 수정해보았습니다.

한번 아래처럼 master 버전으로 설치해서 테스트 해보시고, 그래도 문제가 해결되지 않는다면 해당 이슈를 다시 열어주세요.

```
git clone https://github.com/elbakramer/koapy.git
cd koapy
pip install .
```

(원래 닫을 생각은 없었는데 제가 설정을 저도 모르는 사이에 해뒀는지 커밋 메시지로 트리거되서 자동으로 닫히네요 ㅎㅎ)

**Comment by hoiwhs** [comment]
정말 감사드립니다. 
알려주신 대로 하니, 잘 동작합니다.
늦은 시간에 빠른 답변 정말 다시 한번 감사드립니다.
하시는 일마다 항상 성공하시길 바랍니다.
