### ISSUE TITLE
3개 주식종목 이상 실시간데이터 수신 요청 후 cancel 시 서버 종료 현상

### ISSUE THREAD

**Issue by thesoomyung** [elbakramer/koapy#36]
안녕하세요?
좋은 라이브러리 만들어주셔서 감사합니다.
실시간 데이터 수신에 문제가 있어보여 리포트 합니다.

3개 종목 이상 실시간 데이터 stream 요청한 후 stream.cancel() 하면  koapy 서버가 죽는 현상이 있습니다.
2개 종목 이하로 실시간데이터 요청을 하면 죽지 않습니다.
아래 테스트 코드 참고하시어 문제 한번 확인해봐주시겠습니까?

## test.py
```python
from time import sleep
from koapy.backend.kiwoom_open_api_plus.grpc.KiwoomOpenApiPlusServiceClient import KiwoomOpenApiPlusServiceClient 
import threading

def getreal(kiwoom, codes,fids,realtype,screenno):
    stream = kiwoom.GetRealDataForCodesAsStream(codes,
                                                fids=fids,
                                                realtype=realtype,
                                                screen_no=screenno)
    sleep(5)
    stream.cancel()

def start():
    print("Started")
    kiwoom = KiwoomOpenApiPlusServiceClient()
    kiwoom.EnsureConnected()

    # codes=["252670","005930"] #<--OK
    codes=["252670","005930","122630"] #<--Not OK, gRPC server get killed.
    fids=[10,11,12,27,28,16,17,18,26,311]
    t=threading.Thread(target=getreal, args=(kiwoom,codes,fids,"주식시세", "1001"))
    t.start()
    t.join()
    print("Finished")

if __name__=="__main__":
    start()
```

## 테스트방법

koapy 버전: 0.4.1
python 버전: Python 3.8.8 (default, Apr 13 2021, 15:08:07) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32

서버: 터미널 띄워서 koapy serve 실행
```shell
koapy serve
```

클라이언트: 다른 터미널 띄워서 위 스크립트 실행
```shell
python test.py
```

**현상**
test.py 가 종료되는 순간 server 가 죽음.
수신종목을 2개 이하로 하면 server 죽지 않음. 

참고로, 장이 열리지 않는 주말에 테스트 한 것입니다.

감사합니다.

**Comment by elbakramer** [comment]
안녕하세요. 버그리포트 감사합니다.

공유주신 샘플 스크립트를 통해 동일한 증상 확인했고,
바로 위의 언급한 커밋을 통해 해당 이슈 수정했습니다.

앱이 죽으면서 별다른 에러메시지 조차 주지 않아서 좀 당황했습니다만,
천천히 찾아가다보니 이벤트 처리과정 중에 `SetRealRemove()` 함수를 잘못 사용하고 있던 문제로 확인되었습니다.

수정사항을 반영한 버전 0.4.2 를 배포하였으니 업데이트 후 다시 한번 테스트 해보시고 알려주세요.

**Comment by thesoomyung** [comment]
> 안녕하세요. 버그리포트 감사합니다.
> 
> 공유주신 샘플 스크립트를 통해 동일한 증상 확인했고,
> 바로 위의 언급한 커밋을 통해 해당 이슈 수정했습니다.
> 
> 앱이 죽으면서 별다른 에러메시지 조차 주지 않아서 좀 당황했습니다만,
> 천천히 찾아가다보니 이벤트 처리과정 중에 `SetRealRemove()` 함수를 잘못 사용하고 있던 문제로 확인되었습니다.
> 
> 수정사항을 반영한 버전 0.4.2 를 배포하였으니 업데이트 후 다시 한번 테스트 해보시고 알려주세요.

문제 해결된것 확인했습니다. 
감사합니다!

**Comment by elbakramer** [comment]
문제 해결되서 이슈 닫습니다.
필요하다면 언제든지 다시 열어주세요.
