### ISSUE TITLE
거래시 Cannot specify order no 에러

### ISSUE THREAD

**Issue by Card2Me** [elbakramer/koapy#4]
**Cannot specify order no 오류 발생**
backtrader live환경을 사용하고 있습니다. 실거래 시에 오류가 발생하여
예제 코드를 돌렸습니다만, 실거래 환경에서 매수 거래를 하는데 오류가 발생하네요.
재밌는건 대략 2주 전에도 모의/실거래 환경에서도 거래가 잘 되었었습니다.

**To Reproduce**
예제를 돌린 상황입니다.

    request_name = '삼성전자 1주 시장가 신규 매수' # 사용자 구분명, 구분가능한 임의의 문자열
    screen_no = '0001'                           # 화면번호
    account_no = account_no                # 계좌번호 10자리, 여기서는 계좌번호 목록에서 첫번째로 발견한 계좌번호로 매수처리
    order_type = 1         # 주문유형, 1 : 신규매수
    code = '005930'
    # 종목코드, 앞의 삼성전자 종목코드
    quantity = 1           # 주문수량, 1주 매수
    price = 0              # 주문가격, 시장가 매수는 가격설정 의미없음
    quote_type = '03'      # 거래구분, 03 : 시장가
    original_order_no = '' # 원주문번호, 주문 정정/취소 등에서 사용

    # 현재는 기본적으로 주문수량이 모두 소진되기 전까지 이벤트를 듣도록 되어있음 (단순 호출 예시)
    for event in context.OrderCall(request_name, screen_no, account_no, order_type, code, quantity, price, quote_type, original_order_no):
            pp.pprint(MessageToDict(event))

** 로그
{'arguments': [{'stringValue': '0001'},
               {'stringValue': '삼성전자 1주 시장가 신규 매수'},
               {'stringValue': 'KOA_NORMAL_BUY_KP_ORD'},
               {'stringValue': ''},
               {'stringValue': ''}],
 'name': 'OnReceiveTrData',
 'singleData': {'names': ['주문번호'], 'values': ['']}}
Traceback (most recent call last):
  File "c:/quant/kiwoom/test.py", line 52, in <module>
    for event in context.OrderCall(request_name, screen_no, account_no, order_type, code, quantity, price, quote_type, original_order_no):     
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 803, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: Cannot specify order no"
        debug_error_string = "{"created":"@1608852409.406000000","description":"Error received from peer ipv6:[::1]:5943","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Exception iterating responses: Cannot specify order no","grpc_status":2}"

**Comment by elbakramer** [comment]
안녕하세요.

#### 에러의 내용

주신 로그를 봤을때, KOA Studio 의 [개발가이드>주문과 잔고처리>기본설명] 내용에서 아래 부분에 해당하는 듯 합니다.

```
[주문]
주문을 내면 OnReceiveTRData(), OnReceiveMsg(), OnReceiveChejan()이벤트가 차례로 호출됩니다.
주문성공 확인
OnReceiveTRData()이벤트는 주로 조회요청후 호출되는 함수이지만 주문시에도 호출되는데 이 이벤트내부에서 주문번호를
얻어올 수 있습니다.그런데 만일 주문이 실패하게 되면 주문번호는 공백("")으로 전달됩니다.
각 주문함수의 리턴값이 0(성공)이여도 장 개시전 주문, 시장가 주문주문가격입력, 호가범위를 벗어난 주문등 다양한 원인으로 주문은 실패할수 있습니다.
```

위의 내용에 따라, 주문 호출 후 발생하는 OnReceiveTRData 이벤트에서 주문번호가 공백인지 아닌지를 체크하는 부분이 있는데요.

https://github.com/elbakramer/koapy/blob/7f865e66a61d6a27c96e62d8b84a2c0ede059cd6/koapy/grpc/event/KiwoomOpenApiEventHandlers.py#L806-L810

여기서 주문번호가 확인이 안되서 에러가 발생한 것으로 보입니다.

#### 에러의 원인

주문이 실패한 원인은 위의 설명에 나열된 원인들을 포함해 다양한 원인들이 있을텐데요.
이거 말고 추가로 제가 추측할만한건, 요청 횟수 제한에 걸린걸 수도 있겠구요.
아니면 자동 로그인 때문에 업데이트 처리 같은게 안되서 주문이 제대로 나가지 않았을 수도 있어 보입니다.

현재 제가 푸시를 하진 않았지만 계속 개발중인 버전을 가지고 주문기능을 테스트 했을때는 별다른 문제를 발견하지 못했습니다.

혹시 사용중이신 버전이나 아니면 커밋 해시값 같은걸 알 수 있을까요?
그럼 좀 더 정확하게 테스트가 가능할 듯 싶습니다.

**Comment by Card2Me** [comment]
안녕하세요. 자세한 설명 감사드립니다.

pip로 설치했으며 버젼은 Version: 0.1.15 입니다.

장마감 시간이긴한데...
- OnReceiveMsg 은 정상처리
- OnReceiveTrData에는 order no가 여전히 없네요.

호출/응답 데이터를 보니, 키움에서 응답을 잘못 주는게 아닌가합니다.
`
{'arguments': [{'stringValue': '0001'},
               {'stringValue': '삼성전자 1주 시장가 신규 매수'},
               {'stringValue': 'KOA_NORMAL_BUY_KP_ORD'},
               {'stringValue': '[505217] 장종료되었습니다'}],
 'name': 'OnReceiveMsg'}
{'arguments': [{'stringValue': '0001'},
               {'stringValue': '삼성전자 1주 시장가 신규 매수'},
               {'stringValue': 'KOA_NORMAL_BUY_KP_ORD'},
               {'stringValue': ''},
               {'stringValue': ''}],
 'name': 'OnReceiveTrData',
 'singleData': {'names': ['주문번호'], 'values': ['']}}
`
 

[GetPCIdentity] VER 3.2.0.0  build 2015.8.12
2021-01-09 06:06:34,553 [DEBUG] OnEventConnect(0) -- KiwoomOpenApiEventHandlers.py:80
2021-01-09 06:06:34,554 [DEBUG] Connected to server -- KiwoomOpenApiTrayApplication.py:134
************************************
request_name: "\354\202\274\354\204\261\354\240\204\354\236\220 1\354\243\274 \354\213\234\354\236\245\352\260\200 \354\213\240\352\267\234 \353\247\244\354\210\230"       
screen_no: "0001"
account_no: "554XXXXXX"
order_type: 1
code: "005930"
quantity: 1
quote_type: "03"

**2021-01-09 06:06:34,687 [DEBUG] OnReceiveMsg('0001', '삼성전자 1주 시장가 신규 매수', 
'KOA_NORMAL_BUY_KP_ORD', '[505217] 장종료되었습니다') -- KiwoomOpenApiEventHandlers.py:71
2021-01-09 06:06:34,690 [DEBUG] OnReceiveTrData('0001', '삼성전자 1주 시장가 신규 매수
', 'KOA_NORMAL_BUY_KP_ORD', '', '') -- KiwoomOpenApiEventHandlers.py:24**
2021-01-09 06:06:34,715 [ERROR] Exception iterating responses: Cannot specify order no -- _server.py:463
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\grpc\_server.py", line 453, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "c:\programdata\anaconda3\lib\site-packages\koapy\grpc\KiwoomOpenApiServiceServicer.py", line 129, in OrderCall
    for response in handler:
  File "c:\programdata\anaconda3\lib\site-packages\koapy\grpc\utils\QueueIterator.py", line 49, in __next__
    return self.next()
  File "c:\programdata\anaconda3\lib\site-packages\koapy\grpc\utils\QueueBasedIterableObserver.py", line 19, in next
    raise error
koapy.openapi.KiwoomOpenApiError.KiwoomOpenApiError: Cannot specify order no

**Comment by icsl-Jeon** [comment]
안녕하세요!
관련해서 설명해주셔서 감사합니다.
혹시 본 error (cannot speicify order no) 가 장마감시간에 `entrypoint.OrderCall(...)` 을 하여도 마찬가지로 발생할 수 있는지 궁금합니다.
