### ISSUE TITLE
FID를 xlsx 대신 csv로 바꾸면 어떨까 합니다.

### ISSUE THREAD

**Issue by dh377** [elbakramer/koapy#71]
**Is your feature request related to a problem? Please describe.**
1. FID number에 대한 label을 추가 하고 싶어도 excel이 없으면, 추가하기 쉽지 않음.
2. xlsx는 로딩하는데 csv보다 시간이 걸림. 바꿔서 테스트해본 결과 0.4초 정도의 로딩 이득이 있음.

**Comment by dh377** [comment]
#72 `pandas.from_excel()`을 `pandas.from_csv()`로 바꾸고 csv로 자료를 변환했습니다. 그리고 KOA Studio를 참조하여 "주문 & 잔고처리"관련 FID-Label을 몇 개 추가 했습니다.

**Comment by elbakramer** [comment]
적어주신 내용들에 동의합니다.
제출해주신 PR 은 머지 처리했습니다.

저도 초기에 CSV 파일 포맷을 생각해보지 않은건 아니지만, 그럼에도 굳이 XLSX 포맷을 선택한 이유가 있긴 한데요.
별건 아니고 UTF-8 인코딩의 CSV 파일을 엑셀로 다루는데 번거로운점이 있어 항목들을 업데이트 할때마다 그게 귀찮아져서 그냥 XLSX 포맷을 채택했었습니다.

구체적으로 UTF-8 인코딩의 CSV 파일을 단순 더블클릭으로 여는 경우 인코딩 이슈가 있어 정상적으로 열지를 못하고요. 
매번 데이터 임포트 방식으로 인코딩을 지정해서 불러와야 했었던게 귀찮아서 그랬네요.
(아마도 한글 언어 기준 EUC-KR 인코딩이 기본인 듯 합니다.)

이번 머지 이후부터는 단순 텍스트 에디터로 편집 가능하니까 크게 이슈는 없을거 같아요.

**Comment by dh377** [comment]
@elbakramer 인코딩 인식 문제로 참여자들간 코드가 꼬일까봐 염려를 많이 하셨군요...

요즘 개발용 텍스트 에디터 인코딩 지원이 워낙 좋으니 인코딩 문제가 생길 여지는 적을 것 같습니다. 오히려 Excel 자체가 문제더라고요 호환성 때문에 특별히 인코딩 옵션을 항상 신경쓰지 않으면, CP949(EUC-KR)로 인코딩을 해서 CSV 저장을 하니까, 어느 순간 파일을 열어보면 깨져있습니다... 마소는 backward compatibility 때문에 이 인코딩 문제를 과감하게 걷어내지를 못하는 것 같더군요... 리눅스 마저도 기본 인코딩이 UTF-8이 된지가 10년도 넘었는데...

대신 MS에서 최근에 나오는 툴 (VSCode)이나 시스템 유틸리티 (PowerShell Core, Windows Terminal)에서는 기본 인코딩을 UTF-8로 맞춰놔서 문자 깨지는 문제가 없는 바람직한 방향으로 가고 있습니다...

또한 Python3가 유니코드 지원을 워낙 잘 해주기 때문에 FID 대신 FID에 연결된 한글 이름을 코드에서 직접 사용하고 있는데요, 아무런 문제가 없습니다. DB에서 마저도 한글을 사용하는데도 문제가 없어요.

개인적으로 코드에 ASCII 이외의 문자 사용을 극히 지양하고 있었지만, 한국 증권 관련 개발을 하면서 클라이언트가  한글을 사용해주기를 바라고 저도 한국 증권 용어를 전부 영어로 번역하는게 너무 큰 일이라 걍 코드에 직접 한글을 써봤는데... 오히려 코드랑 데이터가 한눈에 딱 구분이 되어보이고... 적어도 파이썬3에서는 나쁘지 않습니다.

훌륭한 코드 공개해주셔서 항상 감사하고요, 건승하시는 좋은 하루 되세요~
