### ISSUE TITLE
stream 두번 같이 쓰면 안되는건가요?

### ISSUE THREAD

**Issue by llIllIllllIIIlllllll** [elbakramer/koapy#82]
실시간 조건식을 불러오고

실시간데이터요청해서 데이터 다루고 싶은데 

```python
for event in cancel_after(stream, 10):
  elif event.name == "OnReceiveRealCondition":
        code = event.arguments[0].string_value
        condition_type = event.arguments[1].string_value
        if condition_type == "I":
            code_inserted = code
            condition_met_code_list.append(code_inserted)
  elif condition_type == "D":
            code_deleted = code
            condition_met_code_list.remove(code_deleted)
   elif event.name == "OnReceiveRealData":
        data = dict(zip(event.single_data.names, event.single_data.values))
        print(data)



stream = entrypoint.GetCodeListByConditionAsStream(condition_name)


stream = entrypoint.GetRealDataForCodesAsStream(
    code_list,
    fid_list,
    opt_type,
    screen_no=None,  # 화면번호, 0000 을 제외한 4자리 숫자 임의로 지정, None 의 경우 내부적으로 화면번호 자동할당
    infer_fids=True,  # True 로 설정 시 주어진 fid_list 를 고집하지 말고 이벤트 처리 함수의 인자로 전달받는 실시간데이터 이름에 따라 유연하게 fid_list 를 추론
    readable_names=True,  # True 로 설정 시 각 fid 마다 숫자 대신 읽을 수 있는 이름으로 변환하여 반환
    fast_parse=False,  # True 로 설정 시 이벤트 처리 함수내에서 데이터 값 읽기 시 GetCommRealData() 함수 호출 대신, 이벤트 처리 함수의 인자로 넘어오는 데이터를 직접 활용, infer_fids 가 True 로 설정된 경우만 유의미함
)
```

이렇게 복사했습니다.

근데 조건식은 잘 표시되는데 

리얼데이터가 안받아져요... ㅠ

어떻게 해야될까요?

**Comment by llIllIllllIIIlllllll** [comment]
실시간조건식 > SetRealReg > 실시간realdata 순서가 이렇게 되는건가요? SetRealReg 이걸 꼭해줘야 realdata로 받을 수 있나요?

**Comment by elbakramer** [comment]
* 공유주신 코드 조각이나 설명으로는 문제가 뭔지 정확히 파악이 어렵습니다.
  실제로 동작 가능해서 다른 사람이 재현 가능한 수준의 코드 혹은 더 구체적인 설명이 필요해 보입니다.
* 직관적으로 봤을 때 KOAPY 에 기능적인 이슈가 있다기 보단 단순 사용법에 대한 문의로 보여집니다.
  추후 사용법과 관련된 질문들은 Issues 탭 보다는 Discussions 탭을 활용하시는 걸 추천 드립니다.
* 코드에서 확인되는 실시간조건식/실시간데이터 API 각각이 따로 반환하는 `stream` 두개를 단순하게 하나의 `for` 루프로 처리하기는 어렵습니다. 위의 코드 예시에서는 정확하지 않지만 뭔가 뒤쪽의 `stream` 할당이 앞의 `stream` 변수를 덮어쓰는 것처럼 보이는데요. 이러면 당연히 둘 중 하나의 이벤트밖에 처리할 수 없습니다.
* 대신 각 `stream` 을 threading/multiprocessing 등을 통해 별도로 처리하면서 둘 사이의 coordination 을 위해 messaging/queueing 등을 도입하시는 것도 한가지 방법이라 생각됩니다.
* 실시간 조건식에서 반환하는 종목코드에 대해서 실시간 데이터를 얻는 걸 원하시는 거라면 말씀 주신 것처럼 `실시간조건식 > SetRealReg > 실시간데이터` 흐름이 맞아 보입니다.
* 다만 실시간조건식이 반환하는 값에 따라 실시간데이터의 대상이 되는 종목코드 목록이 동적으로 바뀌는 환경으로 보이기 때문에 위의 `GetRealDataForCodesAsStream()` 함수보다는 [`BidirectionalRealCall()`](https://github.com/elbakramer/koapy/blob/c560046b9973d06a47dceba47a366e3a1d3ce438/koapy/backend/kiwoom_open_api_plus/grpc/KiwoomOpenApiPlusServiceServicer.py#L260) 따위의 함수를 활용하는 것도 좋아 보입니다.
