### ISSUE TITLE
opt10060이 동작하지 않아서 문의 드립니다.

### ISSUE THREAD

**Issue by hermian** [elbakramer/koapy#95]
**Describe the bug**
아래 코드 수행시 응답이 없습니다.
```python
request_name = "종목별투자자기관별차트요청"
tr_code = "opt10060"
screen_no = "0001"
inputs = {
    '일자': "20220909",
    '종목코드': "005930",
    '금액수량구분': "2",
    '매매구분': "0",
    '단위구분': "1",
}

for event in entrypoint.TransactionCall(request_name, tr_code, screen_no, inputs):
    columns = event.multi_data.names
    records = [values.values for values in event.multi_data.values]
    data = pd.DataFrame.from_
```
아래 Screenshot에 보면 멀티데이터로 정보가 조회 되어야 할것 같은데 싱글 데이터로 조회됩니다.
처음 사용하는 거라 맞게 한건지 자신이 없습니다 --;;

**Screenshots**
![image](https://user-images.githubusercontent.com/4395214/189586333-5825e24d-b1df-4375-9b04-18ad6fcf58b8.png)
![image](https://user-images.githubusercontent.com/4395214/189587372-ecdc5a55-5103-49eb-a1dc-018e9dccb123.png)

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Python Version: [Python 3.8.12 32bit]
 - KOAPY Version: [0.8.4]

**Additional context**

**Comment by elbakramer** [comment]
안녕하세요. 상세한 버그 리포트 감사합니다.

사용하신 방식과 관련해서는 딱히 잘못된 부분은 없어 보이고, 결국 KOAPY 자체의 문제로 확인되었습니다.
크게는 아래 두가지가 문제로 보이는데요.

1. 싱글데이터/멀티데이터 관련 문서와 메타정보에서 차이
2. `OPT10060` TR 호출시 응답없음

각각 차례로 원인과 해결방식 관련해 설명드리겠습니다.

#### 1. 싱글데이터/멀티데이터 관련 문서와 메타정보에서 차이

먼저 1번의 경우는 사실 지금까지는 싱글데이터만/멀티데이터만 존재하는 TR의 경우 그 둘을 구분할 수 가 없어서
내부적으로 싱글데이터로만 파싱하던게 표면적으로 나타난 문제입니다.

대신 이후 데이터 처리 과정에서는 내부적으로 레코드가 여러개로 반환되는 경우
이걸 멀티데이터겠거니 하고 유추해 수정되어 동작하는 방식이었기 때문에 실제 데이터 파싱에는 문제가 없었을거구요.

대신 해당 리포트를 받고 좀 더 살펴보다 보니 위의 두가지 경우를 구분할 수 있는 점을 발견해서 해당 내용을 작업했고,
최신 버전에서는 싱글데이터/멀티데이터 관련 알맞게 표기되도록 수정되었습니다.

https://github.com/elbakramer/koapy/blob/ff982dbfc15beab6aec98973c205fe8851e755a5/koapy/backend/kiwoom_open_api_plus/core/KiwoomOpenApiPlusTrInfo.py#L287-L294

#### 2. `OPT10060` TR 호출시 응답없음

이건 저도 몰랐다가 해당 이슈 관련 살펴보면서 발견한건데요.
TR 호출을 위한 Input 값 설정 시 `SetInputValue()` 함수를 호출하는 순서가 중요한 것 같습니다.

구체적으로 문서나 KOAStudio 에서 표기된 Input 순서대로 값을 설정해야 정상적으로 동작합니다.
해당 이슈에서는 그 Input 설정 순서가 틀려서 응답이 없게 된 것으로 확인됩니다.

왜 순서가 틀리게 되었냐까지 설명하자면 좀 복잡한데요. 최대한 간단하게 설명드리자면,
`TransactionCall()` 함수의 `inputs` 가 KOAPY gRPC 서버로 전송되는 과정에서 순서가 뒤섞여버려서 그렇습니다.

관련해서 사용자가 어떤식으로 입력하더라도 내부적으로 알맞은 순서로 입력값을 설정하도록 수정했고
해당 케이스에 대해 정상동작까지 확인하였습니다.

![image](https://user-images.githubusercontent.com/12024377/189903561-46c3640b-8a4b-4ded-a5d2-8b12b93f275b.png)

https://github.com/elbakramer/koapy/blob/ff982dbfc15beab6aec98973c205fe8851e755a5/koapy/backend/kiwoom_open_api_plus/core/KiwoomOpenApiPlusQAxWidgetMixin.py#L481-L511

최신 버전 (v0.9.0) 으로 업데이트 후 이슈 해결되는지 테스트 부탁드리겠습니다.

**Comment by hermian** [comment]
버전업하고 정상 수행하는 것을 확인 했습니다. 감사합니다.

그런데 종목 하나 받는데도 엄청나게 오래 걸리는데 정상인걸까요?
5번 데이터를 받으면 **약 17초씩 sleep**하는 것 같은데요. 삼성전자 하나 받는데요...10여분이 훌쩍 더 걸리네요.  :(....

이건 검색해보니 이유가 있는 거군요. 
```
조회 차단에 대한 키움증권의 공식적인 답변
서버리스크를 회피하면서, OpenAPI 의 모든 고객분들께서 조회 차단을 회피하는 가이드는 아래와 같습니다.
(1초당 5회로 기작업되어 있다는 전제하에 이를 기준으로 한 가이드 입니다.)
- 1초당 5회 조회를 1번 발생시킨 경우 : 17초대기
- 1초당 5회 조회를 5연속 발생시킨 경우 : 90초대기
- 1초당 5회 조회를 10연속 발생시킨 경우 : 3분(180초)대기
```

```
2022-09-17 22:01:30,552 [DEBUG] Rate limiting function call CommRqDataWithInputs(...), sleeping for 17.391000 seconds... - QRateLimitedExecutor.py:79
2022-09-17 22:01:30,590 [DEBUG] OnReceiveTrData('0001', '종목별투자자기관별차트요청', 'opt10060', '', '2') -
 KiwoomOpenApiPlusLoggingEventHandler.py:22
2022-09-17 22:01:47,986 [DEBUG] OnReceiveTrData('0001', '종목별투자자기관별차트요청', 'opt10060', '', '0') -
 KiwoomOpenApiPlusLoggingEventHandler.py:22
2022-09-17 22:01:48,222 [DEBUG] OnReceiveTrData('0001', '종목별투자자기관별차트요청', 'opt10060', '', '0') -
 KiwoomOpenApiPlusLoggingEventHandler.py:22
2022-09-17 22:01:48,395 [DEBUG] OnReceiveTrData('0001', '종목별투자자기관별차트요청', 'opt10060', '', '0') -
 KiwoomOpenApiPlusLoggingEventHandler.py:22
2022-09-17 22:01:48,422 [DEBUG] OnReceiveTrData('0001', '종목별투자자기관별차트요청', 'opt10060', '', '0') -
 KiwoomOpenApiPlusLoggingEventHandler.py:22
2022-09-17 22:01:48,578 [DEBUG] Rate limiting function call CommRqDataWithInputs(...), sleeping for 17.375000 seconds... - QRateLimitedExecutor.py:79
```

**그리고 마지막으로 혹시 일정기간만 받을 수 있는 방법은 없는지요? 예를 들면 20220101~현재까지를 받고 싶습니다만...**
현재 처럼 하면 무조건 모든 데이터를 다 받아야 해서요 ^^

**Comment by elbakramer** [comment]
> **그리고 마지막으로 혹시 일정기간만 받을 수 있는 방법은 없는지요? 예를 들면 20220101~현재까지를 받고 싶습니다만...** 현재처럼 하면 무조건 모든 데이터를 다 받아야 해서요 ^^

일반적으로 시간 축에서 멀티데이터로서 반환하는 TR들은 입력값으로 주는 기준일자가 최신일자가 되고, 거기서부터 과거로 거슬러 올라가며 데이터를 받게 됩니다. 그리고 현재 구현상 별도의 제한이 없다면 더이상 받을 레코드가 없을 때까지 계속해서 데이터를 이어서 요청하도록 되어 있습니다.

따라서 말씀주신 것처럼 시작일자를 제한하고 싶다면, 매 결과에서 데이터가 충분하게 받아졌는지 테스트하고, 만약 충분하다면 더이상 추가요청을 하지 않도록 제한할 필요가 있습니다.

크게 두가지 방법이 있습니다.

1. `stop_condition` 옵션 활용

아래처럼 옵션값을 만들어:

```python
stop_condition = {
    "name": "일자",
    "comparator": "<",
    "value": "20220101",
}
```

아래처럼 호출합니다:

```python
for event in entrypoint.TransactionCall(request_name, tr_code, screen_no, inputs, stop_condition=stop_condition):
    ...
```

그렇게 하면 내부적으로 각 행마다 지정된 열의 값을 주어진 값과 비교하며,
비교 결과가 참인 행이 발견되는 즉시 추가요청을 중단하고, 해당 행을 **포함하지 않는** 나머지 결과를 반환합니다.

여기서는 문자열 비교를 통해 "2022-01-01 보다 더 오래된 행이 발견되면" 의 조건으로 이해하시면 될 것 같습니다.

관련 내부 동작은 아래 부분을 참고하세요:

https://github.com/elbakramer/koapy/blob/ff982dbfc15beab6aec98973c205fe8851e755a5/koapy/backend/kiwoom_open_api_plus/grpc/event/KiwoomOpenApiPlusTrEventHandler.py#L131-L135

3. `stream.cancel()` 사용

비슷한 동작이지만 조건판단 및 추가요청 중단 처리를
KOAPY gRPC 서버가 아닌 클라이언트에서 하는 것에서 앞의 방식과 차이가 있습니다.

단순 컬럼 값 비교를 넘어 좀 더 복잡한 조건처리가 필요할 때도 비슷하게 사용할 수 있습니다.

```python
import operator

name = "일자"
comparator = operator.lt
value = "20220101"

stream = entrypoint.TransactionCall(request_name, tr_code, screen_no, inputs)

for event in stream:
    columns = event.multi_data.names
    records = [values.values for values in event.multi_data.values]
    data = pd.DataFrame.from_records(records, columns=columns)
    
    should_stop = data[name].apply(lambda row_value: comparator(row_value, value)).any()    
    
    if should_stop:
        stream.cancel()
        break
```

다만 KOAPY gRPC 서버에서는 해당 조건을 모르고 계속 요청하는 와중에
클라이언트가 중단 요청을 하면 기존에 처리하던걸 중단하는 것이기 때문에
조회 차단 Rate Limiting 관점에서 불필요한 요청으로 인한 요청 횟수의 낭비가 발생할 수도 있습니다.

또한 이 경우 제한일자 보다 오래된 잉여 데이터의 처리는 클라이언트에서 별도로 해주어야 합니다.

**Comment by hermian** [comment]
감사합니다.
